"""The command-line interface.

The property worth testing is not that the commands run, but that **producing a
result always produces a manifest**. The manifest is the reproducibility
contract, and making it a side effect rather than an opt-in flag is what stops
an undocumented number being generated by forgetting an argument.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from tfidf_stability.cli.commands import load_config
from tfidf_stability.cli.main import main
from tfidf_stability.utils.hashing import hash_file

REPO = Path(__file__).resolve().parents[1]
CORPUS = REPO / "tests" / "fixtures" / "mini_corpus.jsonl"


def build(tmp_path: Path) -> Path:
    out = tmp_path / "mini.tfsx"
    assert main(["build-corpus", str(CORPUS), "-o", str(out)]) == 0
    return out


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
def test_the_default_config_loads_and_carries_its_digest() -> None:
    """A manifest must record *which* config produced a result, not only its
    values -- so a comment change is visible too, and the comments carry the
    spec_addenda citations."""
    config = load_config()
    assert config["_source"] == "default.yaml"
    assert config["_digest"] == hash_file(REPO / "configs" / "default.yaml", text=True)


def test_the_default_config_matches_the_code_defaults() -> None:
    """A config that drifted from the code would silently describe a run that
    never happened."""
    from tfidf_stability.preprocessing.tokenise import DEFAULT_PATTERN
    from tfidf_stability.ranking.sort_keys import PI, PI_ALT

    config = load_config()
    assert config["preprocessing"]["token_pattern"] == DEFAULT_PATTERN
    assert tuple(config["ranking"]["pi_priority"]) == PI.priority
    assert tuple(config["ranking"]["pi_alt_priority"]) == PI_ALT.priority


def test_tau_has_no_default_only_a_flagged_provisional_value() -> None:
    """Section 7.1 makes every tie-break result conditional on tau, and tau is
    derived from the measured noise floor. A plain ``tau:`` key would let a run
    inherit an unjustified constant without the caller noticing."""
    evaluation = load_config()["evaluation"]
    assert "tau" not in evaluation
    assert "tau_provisional" in evaluation
    assert "tau_sweep" in evaluation


def test_every_ablation_names_the_field_it_varies() -> None:
    import yaml

    ablations = yaml.safe_load((REPO / "configs" / "ablations.yaml").read_text(encoding="utf-8"))
    for name, entry in ablations.items():
        assert "vary" in entry, f"{name} does not say what it varies"
        assert "values" in entry, f"{name} has no values"
        assert "description" in entry, f"{name} is undocumented"


# ---------------------------------------------------------------------------
# build-corpus
# ---------------------------------------------------------------------------
def test_building_a_corpus_writes_a_model_and_a_manifest(tmp_path: Path) -> None:
    out = build(tmp_path)
    assert out.exists()
    assert out.with_suffix(".json").exists(), "the readable sidecar"
    assert out.with_suffix(".manifest.json").exists(), "the reproducibility contract"


def test_the_manifest_records_everything_that_could_move_a_number(tmp_path: Path) -> None:
    out = build(tmp_path)
    manifest = json.loads(out.with_suffix(".manifest.json").read_text(encoding="utf-8"))

    assert manifest["run_kind"] == "build_corpus"
    assert manifest["dataset"]["sha256"] == hash_file(CORPUS, text=True)
    assert manifest["config"]["_digest"]
    # The stopword list decides the vocabulary, so editing it must be visible.
    assert manifest["preprocessing"]["stopwords"]["digest"]
    assert manifest["preprocessing"]["digest"]
    assert manifest["model"]["model_digest"]
    assert manifest["parameters"]["reduction"] == "naive"
    assert manifest["parameters"]["log_impl"] == "correctly_rounded"
    assert manifest["manifest_digest"]


def test_building_twice_produces_identical_bytes(tmp_path: Path) -> None:
    """The container carries nothing from the environment."""
    a, b = tmp_path / "a" / "m.tfsx", tmp_path / "b" / "m.tfsx"
    for target in (a, b):
        assert main(["build-corpus", str(CORPUS), "-o", str(target)]) == 0
    assert a.read_bytes() == b.read_bytes()


# ---------------------------------------------------------------------------
# verify
# ---------------------------------------------------------------------------
def test_verify_accepts_a_model_matching_its_manifest(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    out = build(tmp_path)
    capsys.readouterr()
    assert main(["verify", str(out)]) == 0
    assert "verified" in capsys.readouterr().out


def test_verify_rejects_a_manifest_that_does_not_match(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    """The check the reproducibility claim rests on."""
    out = build(tmp_path)
    manifest_path = out.with_suffix(".manifest.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["model"]["model_digest"] = "0" * 64
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")

    assert main(["verify", str(out)]) == 1
    assert "MISMATCH" in capsys.readouterr().out


def test_verify_reports_a_non_reproducible_build_as_a_failure(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    """A fast-math build must not pass verification.

    The obvious implementation of this check -- ``native is None or True`` --
    is always true, which would report every build as reproducible.
    """
    out = build(tmp_path)
    manifest_path = out.with_suffix(".manifest.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["environment"]["native"] = {
        "compiler_id": "GNU",
        "reproducible": False,
        "fast_math": True,
    }
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")

    assert main(["verify", str(out)]) == 1
    assert "reproducible    : False" in capsys.readouterr().out


def test_verify_without_a_manifest_fails_cleanly(tmp_path: Path) -> None:
    out = build(tmp_path)
    out.with_suffix(".manifest.json").unlink()
    assert main(["verify", str(out)]) == 2


# ---------------------------------------------------------------------------
# inspect, info, schema
# ---------------------------------------------------------------------------
def test_inspect_exposes_the_intermediates(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    """README section 1.2 requires intermediates to stay inspectable."""
    out = build(tmp_path)
    capsys.readouterr()  # discard build-corpus's output; only the JSON follows
    assert main(["inspect", str(out), "d3"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["doc_id"] == "d3"
    assert payload["terms"]
    for term in payload["terms"]:
        assert {"token", "term_id", "df", "idf", "tf", "weight"} <= set(term)


def test_inspect_rejects_an_unknown_document(tmp_path: Path) -> None:
    assert main(["inspect", str(build(tmp_path)), "nope"]) == 2


def test_info_reports_the_float_environment(capsys) -> None:  # type: ignore[no-untyped-def]
    capsys.readouterr()
    assert main(["info", "--json"]) == 0
    payload = json.loads(capsys.readouterr().out)
    assert payload["environment"]["float"]["mantissa_dig"] == 53
    assert payload["environment"]["float"]["subnormals_supported"] is True


def test_schema_describes_the_container(capsys) -> None:  # type: ignore[no-untyped-def]
    capsys.readouterr()
    assert main(["schema"]) == 0
    fields = {f["name"] for f in json.loads(capsys.readouterr().out)}
    assert {"indptr", "indices", "values", "idf", "norms", "tokens", "doc_ids"} <= fields


def test_no_arguments_prints_help_and_fails() -> None:
    assert main([]) == 1


def test_version(capsys) -> None:  # type: ignore[no-untyped-def]
    from tfidf_stability import __version__

    assert main(["--version"]) == 0
    assert capsys.readouterr().out.strip() == __version__


@pytest.mark.parametrize("command", ["build-corpus", "inspect", "verify", "info", "schema"])
def test_every_command_is_registered(command: str) -> None:
    from tfidf_stability.cli.main import build_parser

    actions = [a for a in build_parser()._actions if hasattr(a, "choices") and a.choices]
    assert any(command in (a.choices or {}) for a in actions)
