"""The deterministic ranking operator, margins and tie groups (section 2.3.1-2.3.3)."""

from tfidf_stability.ranking.attributes import (
    DEFAULT_SPECS,
    AttributeDType,
    AttributeSpec,
    AttributeTable,
    Direction,
    MissingPolicy,
)
from tfidf_stability.ranking.distances import (
    FKS_PENALTY,
    TopKComparison,
    compare_top_k,
    fks_max,
    inversion_count,
    jaccard_distance,
    kendall_fks,
    kendall_tau_distance,
    top_k_disagreement,
)
from tfidf_stability.ranking.margins import (
    Margin,
    MarginSummary,
    adjacent_gaps,
    boundary_margin,
    margin_profile,
    min_adjacent_margin_top,
    summarise,
)
from tfidf_stability.ranking.ranker import (
    Ranking,
    Selection,
    rank,
    rank_all_operators,
    rank_top_k,
    sorted_scores_desc,
)
from tfidf_stability.ranking.sort_keys import (
    OPERATORS,
    PI,
    PI_ALT,
    PI_SCORE,
    SortKeySpec,
    build_keys,
)
from tfidf_stability.ranking.tie_groups import (
    TieGroupIndex,
    chain_inflation_ratio,
    tie_ball_interval,
    tie_chains,
    tie_cliques,
)

__all__ = [
    "DEFAULT_SPECS",
    "FKS_PENALTY",
    "OPERATORS",
    "PI",
    "PI_ALT",
    "PI_SCORE",
    "AttributeDType",
    "AttributeSpec",
    "AttributeTable",
    "Direction",
    "Margin",
    "MarginSummary",
    "MissingPolicy",
    "Ranking",
    "Selection",
    "SortKeySpec",
    "TieGroupIndex",
    "TopKComparison",
    "adjacent_gaps",
    "boundary_margin",
    "build_keys",
    "chain_inflation_ratio",
    "compare_top_k",
    "fks_max",
    "inversion_count",
    "jaccard_distance",
    "kendall_fks",
    "kendall_tau_distance",
    "margin_profile",
    "min_adjacent_margin_top",
    "rank",
    "rank_all_operators",
    "rank_top_k",
    "sorted_scores_desc",
    "summarise",
    "tie_ball_interval",
    "tie_chains",
    "tie_cliques",
    "top_k_disagreement",
]
